# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table='testapp_testmodel',
        ),
    ]
