# Generated by Django 3.0.9 on 2020-08-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_auto_20190722_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True,
                                       verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True,
                                       verbose_name='modified'),
        ),
    ]
